config/routes.rb
Rails.application.routes.draw do
  resources :photos
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  root "events#index"

  resources :events do
    resources :comments, only: %i[ create destroy ]
    resources :subscriptions, only: %i[ create destroy ]
    resources :photos, only: %i[ create destroy ]

    post :show, on: :member
  end

  resources :users, only: %i[ show edit update ]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :event
  belongs_to :user, optional: true

  validates :body, presence: true
  validates :user_name, presence: true, unless: -> { user.present? }

  def user_name
    if user.present?
      user.name
    else
      super
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_event, only: %i[ create destroy ]
  before_action :set_comment, only: %i[ destroy ]

  def create
    @new_comment = @event.comments.build(comment_params)
    @new_comment.user = current_user

    if @new_comment.save
      NotifySubscribersJob.perform_later(@new_comment)

      redirect_to @event, notice: I18n.t("controllers.comments.created")
    else
      render "events/show", alert: I18n.t("controllers.comments.error")
    end
  end

  def destroy
    message = { notice: I18n.t("controllers.comments.destroyed") }

    if current_user_can_edit?(@comment)
      @comment.destroy!
    else
      message = { alert: I18n.t("controllers.comments.error") }
    end

    redirect_to @event, message
  end

  private

  def set_event
    @event = Event.find(params[:event_id])
  end

  def set_comment
    @comment = @event.comments.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body, :user_name)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="buffer-bottom">
  <p><%= comment.body %></p>
  <p>
    <div class="col-md-5 psn-rltv text-left">
      <% if comment.user.present? %>
        <%= render partial: "users/user", object: comment.user %>
      <% else %>
        <em><strong><%= comment.user_name %></strong></em>
      <% end %>
    <div class="text-left"><%= l comment.created_at, format: :short %></div>
      <% if current_user_can_edit?(comment) %>
        <%= button_to event_comment_path(comment.event, comment),
        method: :delete,
        data: { confirm: t("comments.comment.destroy_confirm"), 
        turbo_confirm: t("comments.comment.destroy_confirm") }, 
        class: "btn btn-outline-danger position-absolute top-50 start-100 translate-middle bi bi-x-circle-fill" do %>
        <% end %>
      <% end %>
    </div>
  </p>
</div>

app/views/comments/_form.html.erb
<%= form_for [@event, comment], data: { turbo: false } do |f| %>
  <%= render partial: "partials/form_errors", locals: { model: comment } %>

  <div class="form-group mt-3">
    <%= f.label :body, t("activerecord.models.comment"), class: "form-label" %>
    <%= f.text_area :body, class: "form-control" %>
  </div>

  <% unless user_signed_in? %>
    <div class="form-group mt-3">
      <%= f.label :user_name, t("activerecord.attributes.user.name"), class: "form-label" %>
      <%= f.text_field :user_name, class: "form-control" %>
    </div>
  <% end %>

  <div class="actions mt-3 mb-3">
    <%= f.submit t("button.comment"), class: "btn btn-primary" %>
  </div>
<% end %>