config/routes.rb
Rails.application.routes.draw do
  resources :photos
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  root "events#index"

  resources :events do
    resources :comments, only: %i[ create destroy ]
    resources :subscriptions, only: %i[ create destroy ]
    resources :photos, only: %i[ create destroy ]

    post :show, on: :member
  end

  resources :users, only: %i[ show edit update ]
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user

  has_many :subscriptions, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :subscribers, through: :subscriptions, source: :user
  has_many :photos, dependent: :destroy

  validates :title, presence: true, length: { maximum: 255 }
  validates :address, presence: true
  validates :datetime, presence: true

  def visitors
    (subscribers + [user]).uniq
  end

  def pincode_valid?(pin2chek)
    pincode == pin2chek
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: %i[ show index ]
  before_action :set_event, except: %i[ index new create ]

  after_action :verify_authorized, except: %i[ index ]

  def index
    @events = Event.all
  end

  def show
    begin
      authorize @event
    rescue Pundit::NotAuthorizedError
      flash.now[:alert] = I18n.t("controllers.events.wrong_pincode") if params[:pincode].present?
      render "password_form"
    end

    @new_comment = @event.comments.build(params[:comment])
    @new_subscription = @event.subscriptions.build(params[:subscription])
    @new_photo = @event.photos.build(params[:photo])
  end

  def new
    @event = Event.new
    authorize @event
  end

  def edit
    authorize @event
  end

  def create
    @event = current_user.events.build(event_params)

    authorize @event

    if @event.save
      redirect_to @event, notice: I18n.t("controllers.events.created")
    else
      render :new
    end
  end

  def update
    authorize @event

    if @event.update(event_params)
      redirect_to @event, notice: I18n.t("controllers.events.updated")
    else
      render :edit
    end
  end

  def destroy
    authorize @event

    @event.destroy

    redirect_to events_path, notice: I18n.t("controllers.events.destroyed")
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :address, :datetime, :description, :pincode)
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def is_subscriber?
    [@event.subscribers, [@event.user]].flatten.include?(current_user)
  end
end

app/views/events/_event.html.erb
<div class="flx-dspl col-sm-12 col-md-6 col-lg-4 mt-3 ">
  <div class="flx-dspl psn-rltv thumbnail wdh-fteen-prc">

    <%= content_tag "div", "", class: "event-background rounded",
      style: "background-image: url(#{asset_path("event_thumb.jpg")})" %>

    <div class="thumbnail-inner event-info-inner text-center rounded wdh-fteen-prc">
      <div class="caption">
        <div class="event-description m-3">
          <h3><%= link_to event.title, event_path(event) %></h3>
          <h3><small><%= l event.datetime, format: :short %></small></h3>
          <div class="buffer-both"><%= event.address %></div>
        </div>
        <div class="mb-3">
          <% event.visitors.each do |user| %>
            <%= image_tag user_avatar(user), class: "sz-small rounded-circle", title: user.name %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<div class="col-lg-12">
  <%= form_with model: @event, data: { turbo: false } do |f| %>
    <%= render partial: "partials/form_errors", locals: { model: @event } %>

    <div class="form-group mt-3">
      <%= f.label :title, t("activerecord.attributes.event.title"), class: "form-label" %>
      <%= f.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group mt-3">
      <%= f.label :address, t("activerecord.attributes.event.address"), class: "form-label" %>
      <%= f.text_field :address, class: "form-control" %>
    </div>

    <div class="form-group mt-3">
      <%= f.label :datetime, t("activerecord.attributes.event.datetime"), class: "form-label" %>
      <p><%= f.datetime_select :datetime, class: "form-control" %></p>
    </div>

    <div class="form-group mt-3">
      <%= f.label :description, t("activerecord.attributes.event.description"), class: "form-label" %>
      <%= f.text_area :description, class: "form-control" %>
    </div>

    <div class="form-group mt-3">
      <%= f.label :pincode, class: "form-label" %>
      <%= f.text_field :pincode, class: "form-control" %>
    </div>

    <div class="actions buffer-bottom mt-3">
      <%= f.submit t("button.save"), class: "btn btn-primary" %>
      <%= t("link.or") %> <%= link_to t("link.back"), events_path %>
    </div>
  <% end %>
</div>

app/views/events/edit.html.erb
<h1><%= t("events.event.edit") %></h1>

<div class="row">
  <div class="col-lg-9">
    <%= render "form" %>
  </div>
</div>

<%= button_to t("button.destroy_event"), event_path(@event), method: :delete, data: { confirm: t("events.event.destroy_confirm"), turbo_confirm: t("events.event.destroy_confirm") },  class: "btn btn-danger mt-3 lm-3" %>

app/views/events/index.html.erb
<h1><%= t("events.all") %></h1>

<div class="row buffer-bottom mt-3">
  <%= render partial: "events/event", collection: @events %>
</div>

app/views/events/new.html.erb
<h1><%= t("events.event.new") %></h1>

<div class="row">
  <div class="col-lg-9">
    <%= render "form" %>
  </div>
</div>

app/views/events/password_form.html.erb
<h1><%= t("events.event.need_pincode") %></h1>

<div class="col-lg-9">
  <%= form_with data: { turbo: false } do %>
    <div class="form-group mt-3">
      <%= label_tag :pincode, t("activerecord.attributes.event.pincode") %>
      <%= text_field_tag :pincode, params[:pincode], class: "form-control" %>
    </div>

    <div class="actions buffer-bottom mt-3 mb-3">
      <%= submit_tag(t("button.sign_in"), class: "btn btn-primary") %>
    </div>
  <% end %>

  <%= link_to t("link.main"), events_path %>
</div>

app/views/events/show.html.erb
<div class="event m-3">
  <div class="event-info row">
    <div class="col-md-12">
      <%= content_tag "div", "", class: "event-background ronded mt-3",
        style: "background-image: url(#{event_photo(@event)})" %>

      <div class="event-info-inner p-3 row rounded mt-3">
        <div class="col-md-6">
          <div class="event-description">
            <h1><%= @event.title %></h1>
            <h3><%= l @event.datetime, format: :short %></h3>
            <h3><small><%= link_to @event.address,
                "https://yandex.ru/maps/?text=#{@event.address}", target: "_blank" %></small></h3>
            <p><%= @event.description %></p>
          </div>

          <% if current_user_can_edit?(@event) %>
            <div class="buffer-both">
              <%= link_to t("link.edit_event"), edit_event_path(@event), class: "btn btn-primary" %>
            </div>
          <% end %>
        </div>
        <div class="col-md-6">
          <div class="map-style" 
               id="map"
               data-address="<%= @event.address %>">
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-8">
    <div class="event-photos">
      <div class="row">
        <%= render partial: "photos/photo", collection: @event.photos.except(@new_photo) %>
      </div>

      <div class="event-photo-form">
        <%= render partial: "photos/form", locals: { photo: @new_photo || @event.photos.build } %>
      </div>
    </div>

    <div class="event-comments">

      <%= render partial: "comments/form",
        locals: { comment: @new_comment || @event.comments.build } %>

      <div class="buffer-both">
        <%= render partial: "comments/comment",
          collection: @event.comments.except(@new_comment) %>
      </div>
    </div>
  </div>

  <div class="col-md-4">
    <div class="event-owner">
      <h4><%= t("events.event.owner") %></h4>
        <p><%= render partial: "users/user", object: @event.user %></p>
    </div>

  <% if @event.subscriptions.except(@new_subscription).any? %>
    <div class="event-subscriptions">
      <h4><%= t("events.event.guests") %></h4>
      <div>
        <p>
        <%= render partial: "subscriptions/subscription",
          collection: @event.subscriptions.except(@new_subscription) %>
        </p>
      </div>
    </div>
  <% end %>

  <% unless is_subscriber? %>
    <div class="event-subscription-form">
      <h4><%= t("events.event.subscribe") %></h4>
      <div>
        <%= render partial: "subscriptions/form", locals: {
          subscription: @new_subscription || @event.subscriptions.build
        } %>
      </div>
    </div>
  <% end %>
  </div>
</div>