config/routes.rb
Rails.application.routes.draw do
  resources :photos
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  root "events#index"

  resources :events do
    resources :comments, only: %i[ create destroy ]
    resources :subscriptions, only: %i[ create destroy ]
    resources :photos, only: %i[ create destroy ]

    post :show, on: :member
  end

  resources :users, only: %i[ show edit update ]
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  EMAIL_REGEXP = /\A[a-zA-Z0-9\-_.]+@[a-zA-Z0-9\-_.]+\z/.freeze

  belongs_to :event
  belongs_to :user, optional: true

  before_validation :downcase_email

  with_options if: -> { user.present? } do
    validates :user_id, uniqueness: { scope: :event_id }
    validate :self_event_subscription
  end

  with_options unless: -> { user.present? } do
    validates :user_name, presence: true
    validates :user_email,
              presence: true,
              format: { with: EMAIL_REGEXP },
              uniqueness: { scope: :event_id }
    validate :existing_user_email_presence
  end

  def user_email
    if user.present?
      user&.email
    else
      super
    end
  end

  def user_name
    if user.present?
      user&.name
    else
      super
    end
  end

  private

  def downcase_email
    user_email&.downcase!
  end

  def existing_user_email_presence
    if User.exists?(email: user_email)
      errors.add(:user_email, :taken)
    end
  end

  def self_event_subscription
    if user_id == event.user.id
      errors.add(:user_id, :unable_self_event_subscription)
    end
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_event, only: %i[ create destroy ]
  before_action :set_subscription, only: %i[ destroy ]

  def create
    @new_subscription = @event.subscriptions.build(subscription_params)
    @new_subscription.user = current_user

    if @new_subscription.save
      EventMailer.subscription(@new_subscription).deliver_later

      redirect_to @event, notice: I18n.t("controllers.subscriptions.created")
    else
      render "events/show", alert: I18n.t("controllers.subscriptions.error")
    end
  end

  def destroy
    message = { notice: I18n.t("controllers.subscriptions.destroyed") }
    if current_user_can_edit?(@subscription)
      @subscription.destroy
    else
      message = { alert: I18n.t("controllers.subscriptions.error") }
    end

    redirect_to @event, message
  end

  private
    def set_subscription
      @subscription = @event.subscriptions.find(params[:id])
    end

    def set_event
      @event = Event.find(params[:event_id])
    end

    def subscription_params
      params.fetch(:subscription, {}).permit(:user_email, :user_name)
    end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_form.html.erb
<%= form_for [@event, subscription], data: { turbo: false } do |f| %>
  <%= render partial: "partials/form_errors", locals: { model: subscription } %>

  <% unless user_signed_in? %>
    <div class="form-group">
      <%= f.label :user_name, t("activerecord.attributes.user.name") %>
      <%= f.text_field :user_name, class: "form-control" %>
    </div>

    <div class="form-group mt-3">
      <%= f.label :user_email, t("attributes.user.email") %>
      <%= f.text_field :user_email, class: "form-control" %>
    </div>
  <% end %>

  <div class="actions mt-3">
    <%= f.submit t("button.subscribe"), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/subscriptions/_subscription.html.erb
<div class="mt-3 subscription psn-rltv">
  <% if subscription.user.present? %>
    <%= render partial: "users/user", object: subscription.user %>
  <% else %>
    <em><%= subscription.user_name %></em>
  <% end %>
  <% if current_user_can_edit?(subscription) %>
    <%= button_to event_subscription_path(subscription.event, subscription),
    method: :delete,
    data: { confirm: t("subscriptions.subscription.destroy_confirm"), 
    turbo_confirm: t("subscriptions.subscription.destroy_confirm") }, 
    class: "btn btn-outline-danger position-absolute top-50 start-100 translate-middle bi bi-x-circle-fill" do %>
    <% end %>
  <% end %>
</div>